remove upper case changes

diff --git a/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg b/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg
--- a/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg
+++ b/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg
@@ -15,8 +15,6 @@
 
 set -e
 
-# SamyGO: include fixes for allow big case chars
-
 # Uncomment for debugging
 #set -x
 
@@ -590,8 +588,8 @@ ipkg_depends() {
 		all_deps="$all_deps $new_pkgs"
 		local new_deps=
 		for pkg in $new_pkgs; do
-			if echo $pkg | grep -q '[^a-zA-Z0-9.+-]'; then
-				echo "ipkg_depends: ERROR: Package name $pkg contains illegal characters (should be [a-zA-Z0-9.+-])" >&2
+			if echo $pkg | grep -q '[^a-z0-9.+-]'; then
+				echo "ipkg_depends: ERROR: Package name $pkg contains illegal characters (should be [a-z0-9.+-])" >&2
 				return 1
 			fi
 			# TODO: Fix this. For now I am ignoring versions and alternations in dependencies.
diff --git a/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg-build b/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg-build
--- a/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg-build
+++ b/oe/trunk/oe/recipes/stage-manager/files/stage-manager-ipkg-build
@@ -9,8 +9,6 @@
 #   For UID debugging it needs a better "find".
 set -e
 
-# SamyGO: include fixes for allow big case chars
-
 version=1.0
 
 ipkg_extract_value() {
@@ -120,8 +118,8 @@ You probably want to chown these to a system user: " >&2
 	disallowed_filename=`disallowed_field Filename`
 	[ "$?" -ne 0 ] && PKG_ERROR=1
 
-	if echo $pkg | grep '[^a-zA-Z0-9.+-]'; then
-		echo "*** Error: Package name $name contains illegal characters, (other than [a-zA-Z0-9.+-])" >&2
+	if echo $pkg | grep '[^a-z0-9.+-]'; then
+		echo "*** Error: Package name $name contains illegal characters, (other than [a-z0-9.+-])" >&2
 		PKG_ERROR=1;
 	fi
 
